use_frameworks!

platform :ios, '9.0'

target 'RmAudit_Example' do
  pod 'RmAudit', :path => '../'
  
  pod 'RMBaseSDK', :path => '/Users/shichangshun/Desktop/framework/RMBaseSDK'

  target 'RmAudit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
